### ISSUE TITLE
[System] FIX Admission

### ISSUE THREAD

**Issue by hibari18** [hibari18/Kiddo-Academy-AEBC#10]
1. Remove the form wizard. - **CANCELLED**
2. Fix form design and formats. **DONE**
3. Add alerts and validations.
4. There should be an Emergency contact form on admission. - **DONE**

**Comment by hibari18** [comment]
ADDITIONAL:

5. Birthday input should be fixed. - **DONE**
6. Requirements for admission ONLY should be showed. **DONE**
7. Add an input for searching the parent, if the applicant already has a sibling who enrolled in the school for the auto-fill of information.

**Comment by Rose-DC** [comment]
3. Add an input for searching the parent, if the applicant already has a sibling who enrolled in the school for the auto-fill of information. - is this gonna be a pop-up message? or is it really gonna be input for searching? or a button for searching?  Im confused :3 just to clarify things.

**Comment by hibari18** [comment]
it's a dropdown where you could search and select the parent

**Comment by hibari18** [comment]
@Rose-DC please fix the other issues of this module. Thanks

**Comment by hibari18** [comment]
8. Age based on birthday inputed. **DONE**
9. Language spoken specified on the two languages.
10. Don't abbreviate words. **DONE**
11. Multiple select parent status and applicant lives with. **DONE**
12. Remove duplicate save applicant button. **DONE**
13. Requirements for different type of student (New and Transferee)

**Comment by hibari18** [comment]
Update: Things to do
- Requirements for different type of student (New and Transferee) - **DONE**
- Add an input for searching the parent, if the applicant already has a sibling who enrolled in the school for the auto-fill of information.
- Fix disabled fields when the user choose different radio button.
- Add alerts and validations.
- Admit student.
