### ISSUE TITLE
[Docu] EDIT Data Flow Diagram

### ISSUE THREAD

**Issue by Rose-DC** [hibari18/Kiddo-Academy-AEBC#16]
1. The naming convention should be fixed.
         E.g. admission -> admit student
2. Remove the promotions (ask Gwen to clarify this)

**Comment by ChristianBataan** [comment]
Need ba talaga tanggalin ang promotion at sectioning parang sabi ni sir pwede naman iistay yun dahil yun ang manual process nila kung tama alala ko

**Comment by hibari18** [comment]
pinapatanggal lang yon don sa boundaries, not on dfd. is there any argument para tanggalin yung promotions sa dfd? @SeptemberFirst di ko na maalala hahahaha
