### ISSUE TITLE
[Docu] EDIT Fishbone

### ISSUE THREAD

**Issue by Rose-DC** [hibari18/Kiddo-Academy-AEBC#17]
1. The main problem will become: Existing system is outdated (their system is functioning and they are using it, but right now, they do not since its outdated)
2. System optimization (ask Gwen, its from her)

**Comment by ChristianBataan** [comment]
![fishbone011318](https://user-images.githubusercontent.com/30663669/34993105-46ae876c-fb0a-11e7-99f3-c463199d9746.png)

**Comment by ChristianBataan** [comment]
please check

**Comment by ChristianBataan** [comment]
fixed
