### ISSUE TITLE
[Docu] EDIT Use Case

### ISSUE THREAD

**Issue by Rose-DC** [hibari18/Kiddo-Academy-AEBC#18]
1. Naming convention
2. the direction of the arrows 
3. add guardian connected to billing and collection
4. Sectioning and Promotion should be remove because our focus is Admission and Enrollment with Billing and Collection.
Note: must follow  the format.

**Comment by Rose-DC** [comment]
Ito pa... ano na??? @jmtorreda1997

**Comment by ChristianBataan** [comment]
fixed
