### ISSUE TITLE
[Docu] EDIT System Boundaries

### ISSUE THREAD

**Issue by Rose-DC** [hibari18/Kiddo-Academy-AEBC#20]
1. Add parent connected to billing and collection

**Comment by ChristianBataan** [comment]
![sysboundary](https://user-images.githubusercontent.com/30663669/34993154-7437a858-fb0a-11e7-84bf-c689aa4da51d.png)

**Comment by ChristianBataan** [comment]
please check

**Comment by Rose-DC** [comment]
okay na yan, antayin na lang natin comment ni sir about dyan
