### ISSUE TITLE
[SYSTEM] ERROR in side menu

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#22]
![image](https://user-images.githubusercontent.com/30663669/35199273-06f1097a-ff37-11e7-8616-dcd05905aae7.png)

**Comment by ChristianBataan** [comment]
kakapull ko lang nyan bakit may error?

**Comment by hibari18** [comment]
this is working well with me
![image](https://user-images.githubusercontent.com/29983285/35207979-cd1f0e0a-ff80-11e7-8f93-b25dfc15e207.png)

please pull again
