### ISSUE TITLE
[SYSTEM] VALIDATION MESSAGES

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#23]
![image](https://user-images.githubusercontent.com/30663669/35199402-07a35c32-ff38-11e7-89f2-f7285230c202.png)

**Comment by Rose-DC** [comment]
Your db is not updated. @ChristianBataan  this is already fixed, long ago. HAHA

**Comment by Rose-DC** [comment]
Ay noooooo pala. mali pala kasi yung inoopen mo. kaloka. maglog-in ka para maayos yung mga links

**Comment by hibari18** [comment]
PAKIUPDATE NG DB AT MAGPULL NG LATEST COMMITS PALAGI. COMMENT HERE PAG MAAYOS NA YUNG SAINYO TSAKA NYO ICLOSE.

**Comment by hibari18** [comment]
same issue with me. palitan nyo yung alert @Rose-DC tapos ipush nyo. thanks
![image](https://user-images.githubusercontent.com/29983285/35208209-0ded9338-ff82-11e7-9e42-913fafbf0bc6.png)

**Comment by Rose-DC** [comment]
paanong palitan? anongipapalit ko? haha
