### ISSUE TITLE
[SYSTEM] Maintenance/ SCHOOL YEAR

### ISSUE THREAD

**Issue by jm158** [hibari18/Kiddo-Academy-AEBC#24]
wala pa talaga yung sa view curriculum?

**Comment by hibari18** [comment]
eto bang repository na to ginagamit mo, tsaka latest na db????

**Comment by jmtorreda1997** [comment]
Yup eto tsaka latest db

**Comment by hibari18** [comment]
wala kasing view curriculum, san mo nakuha yan?
![image](https://user-images.githubusercontent.com/29983285/35208269-6e5e1f94-ff82-11e7-9ade-869c79dcb1d1.png)
![image](https://user-images.githubusercontent.com/29983285/35208271-73597f16-ff82-11e7-8584-5a50a95456b3.png)
seriously eto lang laman nyan

**Comment by jmtorreda1997** [comment]
Mali ata yung na QA ko.

**Comment by hibari18** [comment]
anyway bakit title is school year? anong issue sa schoolyear?

**Comment by jmtorreda1997** [comment]
Yung curriculumv2 kasi nakalagay sa link kanina sorry

**Comment by hibari18** [comment]
so walang issue sa school year?

**Comment by jmtorreda1997** [comment]
Yup, sorry.

**Comment by jmtorreda1997** [comment]
Kasi nakita ko kanina don sa issue na pinost ni kuya yung curriculumv2 an itetest kaya ayun din tinest ko

**Comment by hibari18** [comment]
sige thanks
