### ISSUE TITLE
[SYSTEM] Maintenance/Curriculum/Add Subject

### ISSUE THREAD

**Issue by jm158** [hibari18/Kiddo-Academy-AEBC#26]
nag error pero nasave yung subject

eto yung nasave
![error](https://user-images.githubusercontent.com/35675414/35204293-23fa5bc6-ff68-11e7-9fe0-b81d1a5bb6c1.jpg)

eto yung error
![message](https://user-images.githubusercontent.com/35675414/35204294-2539c6f2-ff68-11e7-8287-ccb8dad7f79d.jpg)

**Comment by hibari18** [comment]
Wrong curriculum link
