### ISSUE TITLE
[SYSTEM] Maintenance/Curriculum/Add Level

### ISSUE THREAD

**Issue by jm158** [hibari18/Kiddo-Academy-AEBC#27]
Tumatanggap talaga ng double entry yan? 

![error](https://user-images.githubusercontent.com/35675414/35204359-88492ada-ff68-11e7-9c01-698a376e43f2.jpg)

**Comment by hibari18** [comment]
is this curriculumv2 again?

**Comment by jmtorreda1997** [comment]
Yup lahat ng curriculum ko na issue is curriculumv2

**Comment by hibari18** [comment]
sige icoclose ko na. paQA nung curriculum.php thanks
