### ISSUE TITLE
[SYSTEM] BILLING

### ISSUE THREAD

**Issue by jm158** [hibari18/Kiddo-Academy-AEBC#31]
May error sakin dito 

![error](https://user-images.githubusercontent.com/35675414/35204700-e4e6a5a4-ff6a-11e7-8a33-f2d144443c4b.jpg)

**Comment by hibari18** [comment]
pagamit nung latest db na inupload ko tas check mo ulit kung same error. gumagana kasi sya sakin. thanks.
![image](https://user-images.githubusercontent.com/29983285/35208724-b16f201a-ff84-11e7-923f-298bb021a2b4.png)
