### ISSUE TITLE
[SYSTEM] FIX Addition of Fees

### ISSUE THREAD

**Issue by jm158** [hibari18/Kiddo-Academy-AEBC#32]
eto lumalabas na error 

![error](https://user-images.githubusercontent.com/35675414/35204762-31f7a244-ff6b-11e7-95a4-df19b27bb7b4.jpg)

**Comment by hibari18** [comment]
ginamit mo ba yung inupload kong db?

**Comment by jmtorreda1997** [comment]
Yup

**Comment by hibari18** [comment]
magpull ka ulit. ganito yung sakin as of now. tapos patest ulit thanks
![image](https://user-images.githubusercontent.com/29983285/35208758-d4997112-ff84-11e7-8133-029c8f16cd84.png)
