### ISSUE TITLE
[SYSTEM] EDIT adding subject design

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#38]
![image](https://user-images.githubusercontent.com/30663669/35245803-6c68714e-ffff-11e7-9712-d80bbea40e47.png)

**Comment by ChristianBataan** [comment]
ganyan talaga yan checkbox? so kapag madami ng level lahat yan madidisplay dyan? hahaba yung window na yan?

**Comment by hibari18** [comment]
yes nakalist lang na ganyan.
