### ISSUE TITLE
[SYSTEM] FIX add subject validation and error message

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#39]
![image](https://user-images.githubusercontent.com/30663669/35246166-b81c64c8-0000-11e8-9e8d-9e0576620ce1.png)

**Comment by Rose-DC** [comment]
done. pero may additional issue. sa UPDATE yung mga levels nawawala yung check. @hibari18  @SeptemberFirst

**Comment by hibari18** [comment]
gumagana sakin tho?
![image](https://user-images.githubusercontent.com/29983285/35267043-fac34b5c-005f-11e8-9e64-fb43d6103410.png)
patingin ako sayoooo

**Comment by Rose-DC** [comment]
![image](https://user-images.githubusercontent.com/30088211/35267278-b43be792-0060-11e8-98d5-0799046930e8.png)

**Comment by Rose-DC** [comment]
di rin nakakpag delete. tinary kong idelee yung ginawa ko kanina di siya na delete

**Comment by hibari18** [comment]
![image](https://user-images.githubusercontent.com/29983285/35267480-5d000912-0061-11e8-8c92-2ba2c83bcf9e.png)
yung process kasi nyan, pag chineckan mo yung grade 3 for example, pwede na itake ng grade 3 yung subject na english. then go ka sa curriculum, update details, then update english. makikita mong nadagdag sya sa curriculum na RBEC.

**Comment by hibari18** [comment]
bale issue is yung delete

**Comment by Rose-DC** [comment]
update na kasi yan. so dapat kung nao yung niadd dun dapat naka check pa rin kapag niedit.

**Comment by Rose-DC** [comment]
diba kapag nag add ka ng subject pipili ka na rin ng level. So dapat sa update mananatili dapat siyang naka check.

**Comment by Rose-DC** [comment]
updates?? regarding sa tanong ko? haha
