### ISSUE TITLE
[SYSTEM] FIX relationship between subject and curriculum details

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#40]
![image](https://user-images.githubusercontent.com/30663669/35246262-1496f6e6-0001-11e8-921d-d090476a35a4.png)

**Comment by ChristianBataan** [comment]
kanina sa subject may checkbox ibig sabihin ba nun eh yun subj na yun ay applicable lang sa level na chinekan ko? pagdating dito sa curriculum details lahat naman pala ng subject pede kong piliin

**Comment by hibari18** [comment]
Please check the present repository on master. Iba na yung curriculum module
