### ISSUE TITLE
[SYSTEM] FIX update curriculum details

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#41]
![image](https://user-images.githubusercontent.com/30663669/35246399-860451ca-0001-11e8-8a37-039811144b55.png)

**Comment by ChristianBataan** [comment]
di ko gets design nito

**Comment by hibari18** [comment]
basta nakalist lang yung subjects. whatever nacheck dyan, mauupdate sa lahat ng level na pinagcreate-an nung subject.
