### ISSUE TITLE
[SYSTEM] FIX validation in add section

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#42]
![image](https://user-images.githubusercontent.com/30663669/35246556-14a9f84e-0002-11e8-9478-65c365457ee6.png)

**Comment by ChristianBataan** [comment]
paano kung number ang sectioning?

**Comment by Rose-DC** [comment]
done. But sa db kasi naka atleast 3 char siya kaya hindi papasaok ang isang char lng. pero pwede ng number yung simula niyan. Di ko una iclose @hibari18 @SeptemberFirst

**Comment by Rose-DC** [comment]
updatess?? @SeptemberFirst  @hibari18
