### ISSUE TITLE
[SYSTEM] FIX alert in delete section

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#43]
![image](https://user-images.githubusercontent.com/30663669/35246786-e51bbfda-0002-11e8-8584-ef968ce04605.png)

**Comment by Rose-DC** [comment]
oi hindi akin yan.. hahaha kay @SeptemberFirst  yan di ko alam ayusin yan. nitry ko tangalin yung din na siya gumana :3 @hibari18
