### ISSUE TITLE
[SYSTEM] FIX fee type

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#45]
![image](https://user-images.githubusercontent.com/30663669/35246996-bc11a5c2-0003-11e8-8055-50bd7bb0df2f.png)

**Comment by hibari18** [comment]
this is the current fee. please pull on master

![image](https://user-images.githubusercontent.com/29983285/35263295-31f46f5a-0053-11e8-8d12-2fb2996b5423.png)
