### ISSUE TITLE
[SYSTEM]Maintenance/Curriculum

### ISSUE THREAD

**Issue by jmtorreda1997** [hibari18/Kiddo-Academy-AEBC#46]
1, Sa add curriculum tatanggap ba talaga dapat ng number sa Curriculum name?
![error](https://user-images.githubusercontent.com/30666152/35257980-9ffafc7e-0037-11e8-8e37-737c2d22bddd.jpg)

![error2](https://user-images.githubusercontent.com/30666152/35258024-d88527a4-0037-11e8-8580-16097b8ebb4c.jpg)

2. Sa level naman
tumatanggap din talaga ng number yung name yung sa Level Name
![error3](https://user-images.githubusercontent.com/30666152/35258095-346999d8-0038-11e8-960e-ec748886943e.jpg)

eto naman tumatanggap ng double entry
![double entry](https://user-images.githubusercontent.com/30666152/35258109-47cf7e16-0038-11e8-85db-1c49fe32d095.jpg)

3. Eto sa Subject naman
hindi ako makapagdelete ng inadd ko na subject
![hindi madelete](https://user-images.githubusercontent.com/30666152/35258162-9da7fdd6-0038-11e8-9115-2a92aa3f5047.jpg)

**Comment by hibari18** [comment]
@Rose-DC nafix mo na ba to? For the entries. Thanks
