### ISSUE TITLE
[SYSTEM] FIX Registrar yung User Transaction/Sectioning

### ISSUE THREAD

**Issue by jmtorreda1997** [hibari18/Kiddo-Academy-AEBC#47]
Nakalagay sa number of student is 2 tapos nung clinick ko yung view students eto lumabas 
![error](https://user-images.githubusercontent.com/30666152/35258388-021a8634-003a-11e8-9320-d1caeba5e61e.jpg)

**Comment by jmtorreda1997** [comment]
Meron pa pala 2 lang yung naka enroll pero nag Fill section pa ako sa section joy, nagkaroon siya ng 2 na students saan galing yung dalawa na yon? eh nailagay na sa love yung 2 na student na naenroll

**Comment by hibari18** [comment]
@SeptemberFirst ako na ba dito? query lang naman to oks lang ahahaha
