### ISSUE TITLE
[System] FIX the datatable in requirement

### ISSUE THREAD

**Issue by Rose-DC** [hibari18/Kiddo-Academy-AEBC#52]
![image](https://user-images.githubusercontent.com/30088211/35269749-de1a0e3e-0067-11e8-88d1-faea8d20d499.png)
 naglagay ako ng mahabang description... hahaha

**Comment by hibari18** [comment]
nasan yung rest ng picture? anong nangyari?

**Comment by Rose-DC** [comment]
nandun pa naman yung ibang ano kasi nga since mahaba yung nasa description di na kita sa screen kailangan pang liitan yung size nung screen... @hibari18

**Comment by hibari18** [comment]
sure fix ko na lang thanks

**Comment by hibari18** [comment]
Fixed. Please check later. :)
