### ISSUE TITLE
[System] Fix Registrar: Admission

### ISSUE THREAD

**Issue by Rose-DC** [hibari18/Kiddo-Academy-AEBC#64]
![image](https://user-images.githubusercontent.com/30088211/35604287-8d3431f0-067c-11e8-87ec-8a62a5b61662.png)

nung pinalitan ko yungnew student ng transferee lumabas siya. baka sa db ko nanaman toh pa check na lang po @hibari18 @SeptemberFirst

**Comment by hibari18** [comment]
hindi pa yan ayos nakaWIP pa yung commit ko lol

**Comment by hibari18** [comment]
Please refer to issue #10 for the update. I've listed the things I still need to fix.
