### ISSUE TITLE
[SYSTEM][REGISTRAR] FIX ADMISSION

### ISSUE THREAD

**Issue by jmtorreda1997** [hibari18/Kiddo-Academy-AEBC#66]
Minor lang naman tanggalin natin yung select all baka mapansin ni sir kahit mock def lang yan madami mapapansin yon tsaka paayos ng pag nakaselect na kusa ng sasara

![untitled](https://user-images.githubusercontent.com/30666152/35846653-78d31340-0b52-11e8-8168-e5a9c1906adb.jpg)

hindi pa din gumagana yung save applicant

![dsadsa](https://user-images.githubusercontent.com/30666152/35846687-9f034bfc-0b52-11e8-86a1-68cdc17684e2.jpg)

**Comment by hibari18** [comment]
Sige thanks

**Comment by hibari18** [comment]
Update: nafix ko na yung sa status at lives with.

**Comment by hibari18** [comment]
Wala bang error message yung pagsasave???? Anong nangyayari pag nagsasave applicant?

**Comment by jmtorreda1997** [comment]
Walang nangyayari pag nagsesave

**Comment by jmtorreda1997** [comment]
I mean nasesave pala pero walang message na lumalabas na succesful

**Comment by hibari18** [comment]
@Rose-DC palagyan to ng alert message thanks
