### ISSUE TITLE
[SYSTEM][ADMIN] FIX Level and Curriculum detail

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#69]
![image](https://user-images.githubusercontent.com/30663669/36000965-bd03c852-0d5f-11e8-88bf-51b1272390c2.png)
![image](https://user-images.githubusercontent.com/30663669/36000989-cf6e6812-0d5f-11e8-967b-90d0d447c79c.png)

di ba dapat ang lalabas lang na subj ay yung chinekan ko?

**Comment by SeptemberFirst** [comment]
d na kasama and curriculum details tab
