### ISSUE TITLE
[SYSTEM][REGISTRAR] 

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#75]
![image](https://user-images.githubusercontent.com/30663669/36002075-cf08a50a-0d63-11e8-9af5-45c060a7b450.png)

wala namang new student na grade 4 na di ba? Siguro lalabas lang dapat yung dropdown kung transferee yung student kasi pag new student dapat automatic na di pa ako nag aral tama ba?

**Comment by SeptemberFirst** [comment]
pwedeng mgkanew kung accelerated
