### ISSUE TITLE
[SYSTEM][REGISTRAR] Fix alert message Admission

### ISSUE THREAD

**Issue by ChristianBataan** [hibari18/Kiddo-Academy-AEBC#76]
![image](https://user-images.githubusercontent.com/30663669/36002296-9a460aa0-0d64-11e8-856f-d8c5124ae4f1.png)

may lumabas na error

**Comment by SeptemberFirst** [comment]
format ng date sa mysql id yyyy-mm-dd. convert nyo nlng sa backend
