### ISSUE TITLE
[SYSTEM] FIX TEACHER USER

### ISSUE THREAD

**Issue by jmtorreda1997** [hibari18/Kiddo-Academy-AEBC#95]
1) nag add ako ng teacher sa Maintenance/Profile
2) nilagyan ko siya ng password sa Utilities/User Account
3) Pag login ko sa inadd ko na teacher may lumabas na errors, nasa baba yung screenshot
![teacher_profile](https://user-images.githubusercontent.com/30666152/37278012-5d323b86-2621-11e8-98d5-d10e9ffe0f2b.jpg)

**Comment by SeptemberFirst** [comment]
ano yung ininput mo sa user account??

**Comment by SeptemberFirst** [comment]
tas patingin ng profile.php mo sa faculty

**Comment by jmtorreda1997** [comment]
ok na pala to nakalimutan ko burahin sorry
